[package]
name = "aurora-index"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
aurora-core = { path = "../aurora-core" }
aurora-dialogue = { path = "../aurora-dialogue" }
aurora-world = { path = "../aurora-world" }
aurora-resource = { path = "../aurora-resource" }
aurora-nwscript = { path = "../aurora-nwscript" }
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
