[package]
name = "aurora-erf"
description = "Lecture défensive des archives ERF/MOD/HAK d'Aurora."
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
aurora-core = { path = "../aurora-core" }
serde.workspace = true
tempfile.workspace = true

[dev-dependencies]
tempfile.workspace = true